{% set version = "1.2.3" %}

package:
    name: pyresample
    version: {{ version }}

source:
    fn: pyresample-{{ version }}.tar.gz
    url: https://github.com/pytroll/pyresample/archive/v{{ version }}.tar.gz
    sha256: d8c80750c73fcba6e5b4c1e5c542729ff097afbaee05ac85f1a27f896c0ec0cd

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
    run:
        - python
        - scipy
        - pyproj
        - numpy x.x
        - configobj
        - pykdtree  # [not win]
        - numexpr
        - matplotlib
        - basemap
        - pillow

test:
    imports:
        - pyresample

about:
  home: https://github.com/mraspaud/pyresample/
  license: LGPL-3.0
  summary: Resampling of remote sensing data in Python

extra:
    recipe-maintainers:
        - ocefpaf
