{% set version = "1.2.9" %}

package:
  name: pyresample
  version: {{ version }}

source:
  fn: pyresample-{{ version }}.tar.gz
  url: https://github.com/pytroll/pyresample/archive/v{{ version }}.tar.gz
  sha256: 7b3e9dcb9fac9ee5e6a6402888cafa701710523406b4289d9f8c538b7e0669ab

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - scipy
    - pyproj
    - numpy x.x
    - configobj
    - pykdtree
    - numexpr
    - matplotlib
    - basemap
    - pillow

test:
  imports:
    - pyresample

about:
  home: https://github.com/pytroll/pyresample/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Resampling of remote sensing data in Python.'

extra:
  recipe-maintainers:
    - ocefpaf
    - davidh-ssec
