travis:
  secure:
    BINSTAR_TOKEN: LnM9W8J12yt+ouBMUo6LSBCfEQDZBJuCl6udOEJ+MZ/+ZE6nnJQ9QuNRPrs8USPPAAHoSNEJ3ESyPx7RRrh8BMgT1TFHTvkFpCvJVdOPx+EOnmVMPx6DzyMD56fKD8Rp4yAgNWWOslIgybeu5PACOnFSmePoUCUCI8s8p+UyrvMiXK3XyENIZ0InoRJIwpj3EQkdC5JgqMtfHI1mf8w4j3wq84zINDtsmiY6AVULkcrKyIV9998/8ufE3thVg4mEVP1PNkYHG3yJ00EPopFbLiTqNtX5wmU3VWIK4ceikOg6/xA8bi+QkMaoTtxUjEJfjof3GixqZj2jNH8VliHds8ABo/D2OCF+/4MDXJBXlkWYcQWW7QzZnrrBTTyiivENSBxEMOWWZyOyz2+KnS+oOFOL8mGwYJzzEFKi1ZRMqvwV2p1AIudkj4TsODfD+71YKcsV3/08/JruKHtR0oGJCUoX5+oYKHi9pFjuwRIZt9KdU6DBhsEZgvrFVgpgjWvx5P4A7TtIpkzp2tMGdPWxaFQHmrTpVHyOOzAeciyRjdCjC3gg36W6PcwZy6zysOjvlYV0GCM0MWdwl3kah8FX0mm/z9ysPzfcSP/B8/x48ZKjZo96BVnpSzhXQiMbeHsoMgS6djDat5JFx3VgzP5V2cURX4nx6vx66DaHKZZrxiw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
